name: Build & Release

on:
  push:
    tags:
      - "*"

jobs:

  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@master

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Build
      run: deno compile --allow-read --allow-write -o rowsplit ./mod.ts

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GH_TOKEN }}
        files: |
          rowsplit
          README.md
